// Regenerates src/shielded/circuit.ts from the compiled circuits in
// circuits/target/. The CLI embeds its circuits rather than shipping them as
// separate assets, which means a recompile is invisible to the CLI until this
// runs — and a stale embed is exactly the bug where the prover derives keys
// with an old formula and every spend fails membership. So: after any
// `nargo compile`, run
//
//   node circuits/embed.mjs
//
// then rebuild. circuits/fixtures.mjs asserts the embed matches target/, so a
// forgotten run fails the fixture gate instead of a live spend.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "src", "shielded", "circuit.ts");

/** The four fields Noir needs at proving time; debug_symbols and file_map are
 * dead weight in a bundled CLI and are dropped. */
function pick(name) {
  const j = JSON.parse(readFileSync(join(HERE, "target", `${name}.json`), "utf8"));
  const { noir_version, hash, abi, bytecode } = j;
  return { noir_version, hash, abi, bytecode };
}

const shield = pick("shield");
const transfer = pick("transfer");

const body = `// GENERATED by circuits/embed.mjs — do not edit by hand.
// Regenerate after any \`nargo compile\` in cli/circuits:
//
//   node circuits/embed.mjs
//
// The compiled circuits are embedded rather than shipped as separate assets:
// the bytecode is small enough that inlining keeps the CLI a single bundled
// file and removes any chance of the artifact going missing at runtime. The
// hash pins which circuit each is: it must stay in step with the verifying key
// baked into the deployed verifier, or every proof this produces is rejected
// on chain. circuits/fixtures.mjs fails if this file drifts from target/.

// The deposit circuit.
//
//   commitment = Poseidon2(mpk, token, value, blinding)
//   inserting it at leaf_index turns old_root into new_root
//
//   public:  token, value, commitment, old_root, new_root, leaf_index
//   private: mpk, blinding, insert_path, insert_right
export const SHIELD_CIRCUIT = ${JSON.stringify(shield, null, 2)} as const;

/** Noir toolchain this circuit was compiled with. Pinned in package.json too. */
export const SHIELD_NOIR_VERSION = ${JSON.stringify(shield.noir_version)};

// The join-split (\`transfer\`) circuit — the one spend circuit for the whole
// pool: it consumes up to two notes and produces exactly two, optionally paying
// a public leg out.
//
//   public:  membership_root, nullifiers[2], out_commitments[2], old_root,
//            new_root, insert_index, public_token, public_value, fee,
//            recipient, relayer, chain_id
//            (the order ShieldedPool.spend passes them)
//   private: sk, token, in_{value,blinding,leaf_index,path,right}[2],
//            out_{mpk,value,blinding,path,right}[2]
export const TRANSFER_CIRCUIT = ${JSON.stringify(transfer, null, 2)} as const;
`;

writeFileSync(OUT, body);
console.log(`embedded shield ${shield.hash}, transfer ${transfer.hash} -> src/shielded/circuit.ts`);
